const {PrismaClient}=require('./backend/node_modules/@prisma/client');
const p=new PrismaClient();
(async()=>{try{const providerId='cmi4tou3o0001yhboxa77gq9i';
  const folders=await p.folder.findMany({where:{providerId}, select:{name:true,specialUse:true,totalCount:true,unreadCount:true}});
  console.dir(folders,{depth:null});
  const totals=await p.email.groupBy({by:['folder'], where:{providerId}, _count:true});
  console.dir(totals,{depth:null});
  const totalEmails=await p.email.count({where:{providerId}});
  console.log('Total emails', totalEmails);
} catch(e){console.error(e);} finally {await p.$disconnect();}})();
